# Site settings
title: Andrea Ordax
email: andreaordax@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://andreaordax.github.io"
twitter_username: andreaordax
github_username:  andreaordax
facebook_username:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
