# Site settings
title: Andrea Ordax
email: andreaordax@gmail.com
description: "Freelance Barcelona-based journalist passionate about social media and new technologies"
baseurl: ""
url: "http://andreaordax.github.io"
twitter_username: andreaordax
github_username:  andreaordax
facebook_username:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
